### ISSUE TITLE
No easy way to go back to sd card and to reformat ssd

### ISSUE THREAD

**Issue by imagidan** [jetsonhacks/rootOnNVMe#10]
I want to reformat the ssd to ntfs or fat to use it in my windows computer, but the target is busy and can't be unmounted. I would like an easy way to change what rootfs points to so I can reformat my ssd.

**Comment by RacecarJ** [comment]
Did you try the instructions in the file setup-service.sh?

**Comment by imagidan** [comment]
Ok, thanks!
