### ISSUE TITLE
Is it right to modify /etc/fstab?

### ISSUE THREAD

**Issue by JohnnyLiu2886** [jetsonhacks/rootOnNVMe#18]
Thanks for your sharing!
First, I format my SSD and create partition on it.
After that, I follow your instruction in the README.md file to run those 2 shell scripts.

However, after reboot, the operating system was timed out waiting for some device.
The followings were come out:
- Dependency failed for /media/ssd
- Dependency failed for Local File Systems.

The jetson Xavier NX entered emergency mode and it could not recover to default mode.
Finally, I edited "/etc/fstab"

There are two rows inside this file.

# <file system>  <mount>  <pass>                    <type>                      <options>       <dump>  <pass>
/dev/root            /                                                 ext4                           defaults           0               1
UUID=ae9dc...    /media/ssd                                 ext4                           defaults 0 0

My solution is to comment out the rows with UUID. After that, everything is worked and I can use the SSD as my root file system.
Is it really a right choice to modify /etc/fstab.

/media/ssd is the default directory of my ssd when I was using sd card as my directory. I think this directory is no longer existed after SSD became the root file system of my jetson xavier NX.

**Comment by jetsonhacks** [comment]
Modifying /etc/fstab should be fine. It seems unlikely that the SSD would use a /mount point without it being specified.

**Comment by JohnnyLiu2886** [comment]
> Modifying /etc/fstab should be fine. It seems unlikely that the SSD would use a /mount point without it being specified.

Thank you
