### ISSUE TITLE
[BUG] Fan becomes uncontrollable

### ISSUE THREAD

**Issue by songrenhe666** [jetsonhacks/rootOnNVMe#23]
Using the script, I successfully transferred EMMC to SSD on Xavier NX, but the fan seems to be uncontrollable. I installed jtop after the transfer.
Do you have any good suggestions?

**Comment by jetsonhacks** [comment]
How are you trying to control the fan?

**Comment by songrenhe666** [comment]
We use the "jtop" command of jetson-stats=3.1.4，jetpack 4.5.1.

**Comment by songrenhe666** [comment]
Sorry, after investigation, I found that the main cause of the fan control problem is the circuit design of the carrier board, and applying this script just makes the phenomenon more obvious.
We have resolved it, thanks for your reply.
