### ISSUE TITLE
[Not Bug] It works fine on Jetson Orin Nano Dev Kit

### ISSUE THREAD

**Issue by youtalk** [jetsonhacks/rootOnNVMe#27]
**Describe the issue**

This issue is just a report. The rootOnNVMe scripts work perfectly on the Jetson Orin Nano Dev Kit.
Thank you very much to make them. They are totally helpful.

```
sudo hdparm -t /dev/nvme0n1 /dev/mmcblk1
[sudo] password for youtalk: 

/dev/nvme0n1:
 HDIO_DRIVE_CMD(identify) failed: Inappropriate ioctl for device
 Timing buffered disk reads: 4088 MB in  3.00 seconds = 1362.06 MB/sec

/dev/mmcblk1:
 HDIO_DRIVE_CMD(identify) failed: Invalid argument
 Timing buffered disk reads: 202 MB in  3.02 seconds =  66.79 MB/sec
```

**What version of L4T/JetPack**
L4T/JetPack version: JetPack 5.1.1

**Which Jetson**
Jetson: Jetson Orin Nano Dev Kit

**Comment by jetsonhacks** [comment]
Thanks for sharing your experience!
